{{- if .Values.usePingConfig.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ include "facile.name" . }}
    helm.sh/chart: {{ include "facile.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-postman
data:
  postman_vars.json: |
    {
        "id": "40199d03-d15c-47e4-b502-8b62f98479d1",
        "name": "Solution-Facile",
        "values": [ 
            {
                "key": "apiLog",
                "value": {{ default "info" .Values.global.api.logLevel | quote }},
                "enabled": true
            },
            {
                "key": "releaseName",
                "value": {{ .Release.Name | quote }},
                "enabled": true
            },
            {
                "key": "globalPwd",
                "value": {{ .Values.global.envs.PING_IDENTITY_PASSWORD | quote }},
                "enabled": true
            },
            {
                "key": "ipAddress",
                "value": {{ .Values.global.envs.IP_ADDRESS | quote }},
                "enabled": true
            },
            {
                "key": "pdAdminUrl",
                "value": "https://{{ include "facile.pdAdminServiceName" . }}:{{ include "pingports.pdConfigPort" . }}",
                "enabled": true
            },
            {
                "key": "pdApis",
                "value": "{{ include "facile.pdAdminServiceName" . }}:{{ include "pingports.pdApiPort" . }}",
                "enabled": true
            },
            {
                "key": "pdLdapHost",
                "value": "{{ include "facile.pdAdminServiceName" . }}",
                "enabled": true
            },
            {
                "key": "pdLdapsPort",
                "value": "{{ include "pingports.pdLdapsPort" . }}",
                "enabled": true
            },
            {
                "key": "pdApiPort",
                "value": "{{ include "pingports.pdApiPort" . }}",
                "enabled": true
            },
            {
                "key": "pazAdminURL",
                "value": "https://{{ include "facile.pazAdminServiceName" . }}:{{ include "pingports.pazConfigPort" . }}",
                "enabled": true
            },
            {
                "key": "pfAdminURL",
                "value": "https://{{ include "facile.pfAdminServiceName" . }}:{{ include "pingports.pfAdminPort" . }}",
                "enabled": true
            },
            {
                "key": "decoderUrl",
                "value": {{ .Values.global.envs.decoderHost | quote }},
                "enabled": true
            },
            {
                "key": "pfBaseURL",
                "value": "https://{{ include "facile.hostname" . }}",
                "enabled": true
            },
            {
                "key": "pfRuntime",
                "value": "{{ include "facile.pfEngineServiceName" . }}:{{ include "pingports.pfEnginePort" . }}",
                "enabled": true
            }{{ if .Values.pingOne.services.enabled }},
            {
                "key": "envName",
                "value": {{ .Values.global.envs.ENVIRONMENT_NAME | quote }},
                "enabled": true
            },
            {
                "key": "pingOneAuthNURL",
                "value": "https://auth.pingone.{{ include "facile.pingOneTld" . }}",
                "enabled": true
            },
            {
                "key": "pingOneMgmtURL",
                "value": "https://api.pingone.{{ include "facile.pingOneTld" . }}",
                "enabled": true
            },
            {
                "key": "pingOneRegion",
                "value": {{ include "facile.pingOneRegion" . | quote }},
                "enabled": true
            },
            {
                "key": "adminEnvId",
                "value": {{ .Values.pingOne.administration.envId | quote }},
                "enabled": true
            },
            {
                "key": "adminUserId",
                "value": {{ .Values.pingOne.administration.adminUserId | quote }},
                "enabled": true
            },
            {
                "key": "pfLogonAppId",
                "value": {{ .Values.pingOne.administration.pfLogonApp.id | quote }},
                "enabled": true
            },
            {
                "key": "pfLogonAppSecret",
                "value": {{ .Values.pingOne.administration.pfLogonApp.secret | quote }},
                "enabled": true
            },
            {
                "key": "adminWorkerId",
                "value": {{ .Values.pingOne.administration.workerApp.id | quote }},
                "enabled": true
            },
            {
                "key": "adminWorkerSecret",
                "value": {{ .Values.pingOne.administration.workerApp.secret | quote }},
                "enabled": true
            },
            {
                "key": "pdConsoleURL",
                "value": "https://{{ include "facile.pdAdminHostname" . }}", 
                "enabled": true
            },
            {
                "key": "pazConsoleURL",
                "value": "https://{{ include "facile.pazAdminHostname" . }}", 
                "enabled": true
            },
            {
                "key": "pazAdminServiceURL",
                "value": "https://{{ include "facile.papServiceName" . }}:{{ include "pingports.papAdminPort" . }}", 
                "enabled": true
            },
            {
                "key": "paConsoleURL",
                "value": "https://{{ include "facile.paAdminHostname" . }}", 
                "enabled": true
            },
            {
                "key": "pcConsoleURL",
                "value": "https://{{ include "facile.pcAdminHostname" . }}", 
                "enabled": true
            },
            {
                "key": "pcAdminURL",
                "value": "https://{{ include "facile.pcAdminServiceName" . }}:{{ include "pingports.pcAdminPort" . }}", 
                "enabled": true
            },
            {
                "key": "pdsAdminURL",
                "value": "https://{{ include "facile.pdsAdminServiceName" . }}:{{ include "pingports.pdsAdminPort" . }}", 
                "enabled": true
            },
            {
                "key": "pfConsoleURL",
                "value": "https://{{ include "facile.pfAdminHostname" . }}", 
                "enabled": true
            }{{ end }}{{ if .Values.useCases.delegatedAdministration.enabled }},
            {
                "key": "delegatorApp",
                "value": "{{ include "facile.delegatorServiceName" . }}:{{ include "pingports.pingDelegatorPort" . }}",
                "enabled": true
            },
            {
                "key": "delegatorSecure",
                "value": true,
                "enabled": true
            }{{- end}}{{ if .Values.capabilities.accessManager.enabled }},
            {
                "key": "paLogonAppId",
                "value": {{ .Values.pingOne.administration.pfLogonApp.id | quote }},
                "enabled": true
            },
            {
                "key": "paLogonAppSecret",
                "value": {{ .Values.pingOne.administration.pfLogonApp.secret | quote }},
                "enabled": true
            },
            {
                "key": "paVirtualHost",
                "value": {{ include "facile.hostname" . | quote }},
                "enabled": true
            },
            {
                "key": "paVirtualPort",
                "value": 443,
                "enabled": true
            },
            {
                "key": "paAdminURL",
                "value": "https://{{ include "facile.paAdminServiceName" . }}:{{ include "pingports.paAdminPort" . }}", 
                "enabled": true
            }{{- end}}{{ if .Values.useCases.userProfiles.enabled }},
            {
                "key": "pdLogonAppId",
                "value": {{ .Values.pingOne.administration.pdLogonApp.id | quote }},
                "enabled": true
            },
            {
                "key": "pdLogonAppSecret",
                "value": {{ .Values.pingOne.administration.pdLogonApp.secret | quote }},
                "enabled": true
            }{{- end}}
        ],
        "_postman_variable_scope": "environment"
    }
{{- end -}}