{{- if .Values.usePingConfig.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ include "facile.name" . }}
    helm.sh/chart: {{ include "facile.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-pingoneldapgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingoneldapgateway
  template:
    metadata:
      labels:
        app: pingoneldapgateway
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: "amd64"
      containers:
        - name: pingoneldapgateway
          image: gcr.io/ping-identity/pingone/pingone-ldap-gateway
          imagePullPolicy: "Always"
          env:
            - name: PING_IDENTITY_ACCEPT_EULA
              value: "yes"
            - name: gatewayCredential
              value: {{ .Values.pingOne.gateways.ldap.credential | quote }}
{{- end -}}