apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ include "facile.name" . }}
    helm.sh/chart: {{ include "facile.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-facile-journeys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facile-journeys
  template:
    metadata:
      labels:
        app: facile-journeys
        app.kubernetes.io/component: am
    spec:
      containers:
        - name: facile-journeys
          image: us-docker.pkg.dev/forgeops-public/images/am:dev
          ports:
            - containerPort: 8080  # Specify the container port here
          # livenessProbe:
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          #   timeoutSeconds: 5
          # readinessProbe:
          #   initialDelaySeconds: 20
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          # startupProbe:
          #   failureThreshold: 40
          #   periodSeconds: 10
          securityContext:
            runAsGroup: 0
            runAsUser: 11111
      nodeSelector: {}
      tolerations: []
      affinity: {}
      securityContext: {}
