apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: {{ include "facile.name" . }}
    helm.sh/chart: {{ include "facile.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # kubernetes.io/ingress.class: nginx-public
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: {{ .Release.Name }}-client-ingress
spec:
  ingressClassName: nginx-public
  tls:
  - hosts:
      - {{ include "facile.hostname" . }}
  rules:
  - host: {{ include "facile.hostname" . }}
    http:
      paths:
      # PingFederate Client Endpoints
      # SAML \ Identity Provider
      - path: /idp/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-pingfederate-engine
            port: 
              number: {{ include "pingports.pfEnginePort" . }}
      # SAML \ Service Provider
      - path: /sp/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-pingfederate-engine
            port: 
              number: {{ include "pingports.pfEnginePort" . }}
      # OAuth \ Authorization Server
      - path: /as/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-pingfederate-engine
            port: 
              number: {{ include "pingports.pfEnginePort" . }}
      # OIDC \ Discovery Endpoint
      - path: /.well-known/openid-configuration
        pathType: Exact
        backend:
          service:
            name: {{ .Release.Name }}-pingfederate-engine
            port: 
              number: {{ include "pingports.pfEnginePort" . }}
      # OIDC JWKS \ Web Services \ AuthN API Explorer
      - path: /pf
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-pingfederate-engine
            port: 
              number: {{ include "pingports.pfEnginePort" . }}
      # Web Service Endpoint
      - path: /ext/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-pingfederate-engine
            port: 
              number: {{ include "pingports.pfEnginePort" . }}
      # Template Assets
      - path: /assets/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-pingfederate-engine
            port: 
              number: {{ include "pingports.pfEnginePort" . }}
      - path: /OAuthPlayground/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-pingfederate-engine
            port: 
              number: {{ include "pingports.pfEnginePort" . }}
      # PingDirectory
      # Directory API
      - path: /directory/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-pingdirectory
            port: 
              number: {{ include "pingports.pdApiPort" . }}
      # Consent API
      - path: /consent/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-pingdirectory
            port: 
              number: {{ include "pingports.pdApiPort" . }}
      # Consent API
      - path: /scim/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-pingdirectory
            port: 
              number: {{ include "pingports.pdApiPort" . }}
      {{- if .Values.useCases.delegatedAdministration.enabled }}
      # Delegated Admin paths
      - path: /dadmin/
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-pingdirectory
            port: 
              number: {{ include "pingports.pdApiPort" . }}
      - path: /delegator
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-pingdelegator
            port: 
              number: {{ include "pingports.pingDelegatorPort" . }}
      {{- end }}
      {{- if .Values.capabilities.accessManager.enabled }}
      # If PA is deployed - everything else goes there...
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-pingaccess-engine
            port: 
              number: {{ include "pingports.paEnginePort" . }}
      {{- end }}