apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-facile-journeys
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "facile.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080  # Match this with the container port
  selector:
    app: facile-journeys
