{{- if .Values.usePingConfig.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ include "sampleCiam.name" . }}
    helm.sh/chart: {{ include "sampleCiam.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-postman
data:
  postman_vars.json: |
    {
        "id": "40199d03-d15c-47e4-b502-8b62f98479d1",
        "name": "Solution-sampleCiam",
        "values": [ 
            {
                "key": "apiLog",
                "value": {{ default "info" .Values.global.api.logLevel | quote }},
                "enabled": true
            },
            {
                "key": "releaseName",
                "value": {{ .Release.Name | quote }},
                "enabled": true
            },
            {
                "key": "globalPwd",
                "value": {{ .Values.global.envs.PING_IDENTITY_PASSWORD | quote }},
                "enabled": true
            },
            {
                "key": "pdAdminUrl",
                "value": "https://{{ include "sampleCiam.pdAdminServiceName" . }}:{{ include "pingports.pdConfigPort" . }}",
                "enabled": true
            },
            {
                "key": "pdApis",
                "value": "{{ include "sampleCiam.pdAdminServiceName" . }}:{{ include "pingports.pdApiPort" . }}",
                "enabled": true
            },
            {
                "key": "pdLdapHost",
                "value": "{{ include "sampleCiam.pdAdminServiceName" . }}",
                "enabled": true
            },
            {
                "key": "pfAdminURL",
                "value": "https://{{ include "sampleCiam.pfAdminServiceName" . }}:{{ include "pingports.pfAdminPort" . }}",
                "enabled": true
            },
            {
                "key": "decoderUrl",
                "value": {{ .Values.global.envs.decoderHost | quote }},
                "enabled": true
            },
            {
                "key": "pfBaseURL",
                "value": "https://{{ include "sampleCiam.hostname" . }}",
                "enabled": true
            },
            {
                "key": "pfRuntime",
                "value": "{{ include "sampleCiam.pfEngineServiceName" . }}:{{ include "pingports.pfEnginePort" . }}",
                "enabled": true
            }{{ if .Values.pingOne.services.enabled }},
            {
                "key": "envName",
                "value": {{ .Values.global.envs.ENVIRONMENT_NAME | quote }},
                "enabled": true
            },
            {
                "key": "pingOneAuthNURL",
                "value": "https://auth.pingone.{{ include "sampleCiam.pingOneTld" . }}",
                "enabled": true
            },
            {
                "key": "pingOneMgmtURL",
                "value": "https://api.pingone.{{ include "sampleCiam.pingOneTld" . }}",
                "enabled": true
            },
            {
                "key": "pingOneRegion",
                "value": {{ include "sampleCiam.pingOneRegion" . | quote }},
                "enabled": true
            },
            {
                "key": "adminEnvId",
                "value": {{ .Values.pingOne.administration.envId | quote }},
                "enabled": true
            },
            {
                "key": "adminUserId",
                "value": {{ .Values.pingOne.administration.adminUserId | quote }},
                "enabled": true
            },
            {
                "key": "pfLogonAppId",
                "value": {{ .Values.pingOne.administration.pfLogonApp.id | quote }},
                "enabled": true
            },
            {
                "key": "pfLogonAppSecret",
                "value": {{ .Values.pingOne.administration.pfLogonApp.secret | quote }},
                "enabled": true
            },
            {
                "key": "adminWorkerId",
                "value": {{ .Values.pingOne.administration.workerApp.id | quote }},
                "enabled": true
            },
            {
                "key": "adminWorkerSecret",
                "value": {{ .Values.pingOne.administration.workerApp.secret | quote }},
                "enabled": true
            },
            {
                "key": "pdConsoleURL",
                "value": "https://{{ include "sampleCiam.pdAdminHostname" . }}", 
                "enabled": true
            },
            {
                "key": "paConsoleURL",
                "value": "https://{{ include "sampleCiam.paAdminHostname" . }}", 
                "enabled": true
            },
            {
                "key": "pdsAdminURL",
                "value": "https://{{ include "sampleCiam.pdsAdminServiceName" . }}:{{ include "pingports.pdsAdminPort" . }}", 
                "enabled": true
            },
            {
                "key": "pfConsoleURL",
                "value": "https://{{ include "sampleCiam.pfAdminHostname" . }}", 
                "enabled": true
            }{{ end }}{{ if .Values.useCases.delegatedAdministration.enabled }},
            {
                "key": "delegatorApp",
                "value": "{{ include "sampleCiam.delegatorServiceName" . }}:{{ include "pingports.pingDelegatorPort" . }}",
                "enabled": true
            },
            {
                "key": "delegatorSecure",
                "value": true,
                "enabled": true
            }{{- end}}{{ if .Values.capabilities.accessManager.enabled }},
            {
                "key": "paLogonAppId",
                "value": {{ .Values.pingOne.administration.pfLogonApp.id | quote }},
                "enabled": true
            },
            {
                "key": "paLogonAppSecret",
                "value": {{ .Values.pingOne.administration.pfLogonApp.secret | quote }},
                "enabled": true
            },
            {
                "key": "paVirtualHost",
                "value": {{ include "sampleCiam.hostname" . | quote }},
                "enabled": true
            },
            {
                "key": "paVirtualPort",
                "value": 443,
                "enabled": true
            },
            {
                "key": "paAdminURL",
                "value": "https://{{ include "sampleCiam.paAdminServiceName" . }}:{{ include "pingports.paAdminPort" . }}", 
                "enabled": true
            }{{- end}}{{ if .Values.useCases.userProfiles.enabled }},
            {
                "key": "pdLogonAppId",
                "value": {{ .Values.pingOne.administration.pdLogonApp.id | quote }},
                "enabled": true
            },
            {
                "key": "pdLogonAppSecret",
                "value": {{ .Values.pingOne.administration.pdLogonApp.secret | quote }},
                "enabled": true
            }{{- end}}
        ],
        "_postman_variable_scope": "environment"
    }
{{- end -}}