apiVersion: v2
name: ping-facile
description: A chart to deploy a CIAM config using Project Facile

type: application

# This is the chart version. This version number should be incremented each time you make changes
# 0.3.0 - Rebranding to Facile. Updating all Products to June 2021 releases; Shifted to Facile Repo URL
# 0.3.1 - Added IP_ADDRESS to Postman configMap -- used to pre-populate the P1 Risk policy
# 0.3.2 - Resolve issue with AP deployments \ Bumped to 2107 images
# 0.3.3 - Resolve issue PD `debug-trace` logger \ Updated to `ping-devops` 0.7.5 \ Bumped to 2108 images
# 0.3.4 - Moved PingData containers to 9.0.0.0-EA-edge
# 0.3.5 - Added Pod for P1 LDAP Gateway \ Bumped to `ping-devops` 0.7.8
# 0.3.6 - Bumped to 2111 & 0.8.1 \ Removed image override for PD | PDS | Console 
# 0.3.7 - Added Vars to disable log4j2 message resolution
# 0.3.8 - Bumped to image to `edge` for log4j fixes
# 0.3.9 - Added `imagePullPolicy: Always` to get latest into deployment
# 0.3.10 - PingData product moved to 9.0 GA
# 0.3.11 - Added PI ASE
# 0.3.12 - Added DaVinci \ Bumped to 0.8.5
# 0.3.13 - PAZ \ PAP --> RC \ Bumped to 0.8.9 & 2202
# 0.3.14 - PAZ \ PAP --> EA Release
# 0.3.15 - Bumping PD \ PDS to 9.1 EA
# 0.3.16 - Adding P1 Fraud
# 0.3.17 - Adding .ca P1 Region
# 0.3.18 - Bumping to 2206 GA versions
# 0.3.19 - Switching to `ping-devops` versions
# 0.3.20 - Bumping `ping-devops` \ Adding DV v2 IK & Fragment
# 0.3.21 - Bumping `ping-devops` \ Attempting to stop evictions of PF Engines
# 0.3.22 - Removing PingOne Fraud collection
version: 0.3.22

# This matches the version of `ping-devops` this chart depends on 
appVersion: 0.9.7

# Use PingIdentity Repo to deploy Product Services \ Deployments
dependencies:
- name: ping-devops
  version: 0.9.7
  repository: https://helm.pingidentity.com
