apiVersion: v2
name: ping-facile
description: A chart to deploy a CIAM config using Project Facile

type: application

# This is the chart version. This version number should be incremented each time you make changes
# 0.3.0 - Rebranding to Facile. Updating all Products to June 2021 releases; Shifted to Facile Repo URL
# 0.3.1 - Added IP_ADDRESS to Postman configMap -- used to pre-populate the P1 Risk policy
# 0.3.2 - Resolve issue with AP deployments \ Bumped to 2107 images
# 0.3.3 - Resolve issue PD `debug-trace` logger \ Updated to `ping-devops` 0.7.5 \ Bumped to 2108 images
# 0.3.4 - Moved PingData containers to 9.0.0.0-EA-edge
# 0.3.5 - Added Pod for P1 LDAP Gateway \ Bumped to `ping-devops` 0.7.8
# 0.3.6 - Bumped to 2111 & 0.8.1 \ Removed image override for PD | PDS | Console 
# 0.3.7 - Added Vars to disable log4j2 message resolution
# 0.3.8 - Bumped to image to `edge` for log4j fixes
# 0.3.9 - Added `imagePullPolicy: Always` to get latest into deployment
# 0.3.10 - PingData product moved to 9.0 GA
# 0.3.11 - Added PI ASE
# 0.3.12 - Added DaVinci \ Bumped to 0.8.5
# 0.3.13 - PAZ \ PAP --> RC \ Bumped to 0.8.9 & 2202
# 0.3.14 - PAZ \ PAP --> EA Release
# 0.3.15 - Bumping PD \ PDS to 9.1 EA
# 0.3.16 - Adding P1 Fraud
# 0.3.17 - Adding .ca P1 Region
# 0.3.18 - Bumping to 2206 GA versions
# 0.3.19 - Switching to `ping-devops` versions
# 0.3.20 - Bumping `ping-devops` \ Adding DV v2 IK & Fragment
# 0.3.21 - Bumping `ping-devops` \ Attempting to stop evictions of PF Engines
# 0.3.22 - Removing PingOne Fraud collection
# 0.3.23 - Adding P1 LDAP Gateway
# 0.3.24 - Testing Postman URLs to new scheme (Unified User Profiles)
# 0.3.25 - Updating Postman URLs
# 0.4.0 - Updating to Dec 2022 releases
# 0.4.1 - Adding PingCentral
# 0.4.2 - Adding SSO to PingCentral
# 0.4.3 - Bumping `ping-devops`
# 0.4.4 - Bumping `ping-devops` \ Disabled PI
# 0.4.5 - Adding limits to PF Engine to attempt to stop evictions
# 0.4.6 - Fixing Ingress for k8s 1.22 \ Bumping `ping-devops`
# 0.4.7 - Testing with Graviton nodes
# 0.4.8 - Bumping to edge (not PF)
# 0.4.9 - Bumping ping-devops - all latest versions
# 0.4.10 - Adding facile-apps image deployment and Ingress paths
# 0.4.11 - Moving PF to new EnvVars for LDAP storage
# 0.4.12 - Removing NodeSelector from PingConfig \ Move Gateway to Docker Hub \ Bump ping-devops
# 0.4.13 - LDAP Gateway - upgrade to 3.0.1
# 0.4.14 - LDAP Gateway - upgrade to 3.0.4 / bumping ping-devops
# 0.5.0 - Updating to Dec 2023 releases
# 0.5.1 - Bumping ping-devops \ Disable PingCentral \ Disable LDAP Gateway
# 0.5.2 - Enabling LDAP Gateway
# 0.5.3 - Updating LDAP Gateway to 3.1.2 ARM \ Bump ping-devops \ PF & PA on edge 
# 0.5.4 - Playing with PingAM

version: 0.5.4-alpha.2

# This matches the version of `ping-devops` this chart depends on 
appVersion: 0.10.5

# Use PingIdentity Repo to deploy Product Services \ Deployments
dependencies:
- name: ping-devops
  version: 0.10.5
  repository: https://helm.pingidentity.com
