apiVersion: v2
name: ping-sample-ciam
description: A chart to deploy a Sample CIAM config using Project Facile

type: application

# This is the chart version. This version number should be incremented each time you make changes
# 0.1.0 - Initial release based on pingidentity/ping-devops 
# 0.1.1 - Adding SERVER_PROFILE_BRANCH=main to values.yaml
# 0.2.0 - Release requires Dec 2020 versions of software
# 0.2.0 - Updated to ping-devops 0.4.x
# 0.2.0 - Added Use Cases - CIBA \ Access Control \ User Profile
# 0.2.1 - Added Verify; Added Name Attribute mappings; Updated ping-devops to 0.4.1
# 0.2.2 - Updated to ping-devops 0.4.3; Added PA Clustering
# 0.2.3 - Added `decoderUrl` variable
# 0.2.4 - Updating dependency
# 0.2.5 - Adding Ingress route for PF OAuthPlayground
# 0.2.6 - moving to :latest to allow time to resolve new rootless images
# 0.2.7 - Moving back to specific release - 2102 Updating ping-devops chart to 0.5.1 - Updated Notes.txt
# 0.2.8 - Bumping dependency to 0.6.2 \ Added PAZ \ Updated to 2104 - non-root (except PF)
# 0.2.9 - Adding PAP SSO pieces (configmap-env-vars)
# 0.2.10 - Removed PAP SSO vars - it breaks the Policy injection
# 0.2.11 - Updating the Liveness check for PAZ
# 0.3.0 - Updating all Products to June 2021 releases
version: 0.3.0

# This is the Product Image versions this chart passes to `ping-devops`
appVersion: 2104

# Use PingIdentity Repo to deploy Product Services \ Deployments
dependencies:
- name: ping-devops
  version: 0.6.2
  repository: https://helm.pingidentity.com
