apiVersion: v2
name: ping-sample-ciam
description: A Helm chart to deploy a Ping CIAM config into a Kubernetes cluster

type: application

# This is the chart version. This version number should be incremented each time you make changes
# 0.1.0 - Initial release based on pingidentity/ping-devops 
version: 0.1.0

# This is the version number of the application being deployed.
appVersion: 1.0.0

# Use PingIdentity Repo to deploy Product Services \ Deployments
dependencies:
- name: ping-devops
  version: ~0.3.0
  repository: https://helm.pingidentity.com
