global:
  ingress:
    enabled: true
    addReleaseNameToHost: subdomain
    defaultDomain: ping-devops.com

pingdirectory:
  enabled: true
  envs: 
    SERVER_PROFILE_URL: https://github.com/cprice-ping/Sample-CIAM.git
    SERVER_PROFILE_PATH: pingdirectory
  logging: INFO
  #ingress:
  #  enabled: false
  container:
    replicaCount: 1
  services:
    https:
      clusterService: true
    apis:
      clusterService: true

pingdataconsole:
  enabled: true

pingfederate-admin:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/cprice-ping/Sample-CIAM.git
    SERVER_PROFILE_PATH: pingfederate   
  logging: INFO
  #ingress:
  #  enabled: false
  services:
    # Allows OIDC callbacks to PF through the GSA Ingress
    # Comment out `admin` section to default to :9999
    admin:
      port: 443
      targetPort: 443

pingfederate-engine:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/cprice-ping/Sample-CIAM.git
    SERVER_PROFILE_PATH: pingfederate
    PF_ADMIN_PORT: "443"
  logging: INFO
  #ingress:
  #  enabled: false

pingdatasync:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/cprice-ping/Sample-CIAM.git
    SERVER_PROFILE_PATH: pingdatasync
  logging: INFO

pingcentral:
  enabled: false
  tlsBlindTrust: true
  tlsVerifyHostnames: false
  envs:
    SERVER_PROFILE_URL: https://github.com/cprice-ping/Sample-CIAM.git 
    SERVER_PROFILE_PATH: pingcentral/logging
    SERVER_PROFILE_PARENT: DATA
    SERVER_PROFILE_DATA_URL: https://github.com/cprice-ping/Sample-CIAM.git
    SERVER_PROFILE_DATA_PATH: pingcentral/external-mysql-db
  logging: INFO

pingaccess:
  enabled: false
  logging: INFO

pingdelegator:
  enabled: true